<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_oreder_title</name>
   <tag></tag>
   <elementGuidId>041328de-4845-42f4-893b-026443f459ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.fontOrder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Page'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3f1ba684-1263-4242-a956-9ad2c897c6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fontOrder</value>
      <webElementGuid>f15c6c29-26fc-48ed-847e-6c163bed9032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order lists: </value>
      <webElementGuid>d1602856-cae8-412a-8151-70af1ea8fa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;row&quot;]/h1[@class=&quot;fontOrder&quot;]</value>
      <webElementGuid>9f28e011-9f53-4b5b-9081-b421a405d909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Page'])[1]/following::h1[1]</value>
      <webElementGuid>2fe971e9-929c-4aea-92eb-634b78892187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number:'])[1]/preceding::h1[1]</value>
      <webElementGuid>c3a05000-a2fc-4899-bb3b-7d1e335ac3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail:'])[1]/preceding::h1[1]</value>
      <webElementGuid>aac6cb20-b939-4253-abc3-ac8ba0fa3dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order lists:']/parent::*</value>
      <webElementGuid>ddd9534e-dfe3-428d-b0bb-0325d196ef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>6d2f5bf3-90f7-4f82-996b-340e1627fbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Order lists: ' or . = 'Order lists: ')]</value>
      <webElementGuid>64dc915b-6129-46c8-8e24-6947853b6f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
