<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_go to login page</name>
   <tag></tag>
   <elementGuidId>a5166631-6007-44ce-bf4d-2d4fdf21f40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-warning.btn-lg.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kitchen')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6adc55c0-79a0-419e-b481-dd4d9d347038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indexKitchen.ejs</value>
      <webElementGuid>1d87e080-27c5-47d9-8989-1c54858df15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-lg active</value>
      <webElementGuid>9675b3fd-88ed-430f-8352-cc210665e3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9c00de8-e908-434a-82f3-4442b7f1ed63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e41799ac-c351-439a-b64a-a328b4da04ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kitchen</value>
      <webElementGuid>25da8484-52c6-4e21-a8cf-878083398273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/a[@class=&quot;btn btn-warning btn-lg active&quot;]</value>
      <webElementGuid>32407bea-4705-4d8d-9cd3-c04214f836ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kitchen')]</value>
      <webElementGuid>8dda85d6-1982-4e4f-8d3c-b98cbd2d6e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select!'])[1]/following::a[1]</value>
      <webElementGuid>ad8297a6-cd94-406d-80da-7ad966240797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connoisseur'])[1]/following::a[1]</value>
      <webElementGuid>62637235-ed00-4ada-8383-e6d51b96dbd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/preceding::a[1]</value>
      <webElementGuid>7ef63bb8-ebed-4624-86c7-4be1edb32284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kitchen']/parent::*</value>
      <webElementGuid>88c5d461-7b06-44c6-bc69-225515f6e2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indexKitchen.ejs')]</value>
      <webElementGuid>9ff18144-d2ab-432b-8db1-a12a101964ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>a3be0c9f-517f-47e1-941f-a8ed55a394fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indexKitchen.ejs' and (text() = 'Kitchen' or . = 'Kitchen')]</value>
      <webElementGuid>3177cc25-3f0f-4328-95ab-cbe379e26ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
