<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Dessert</name>
   <tag></tag>
   <elementGuidId>301975f9-162f-4748-b819-46c906a77524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dessert > h2.section-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='dessert']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>245e4978-c383-4a78-a46d-a5f435049851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>525caa19-80be-44d9-a159-c80ad7dd2071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dessert</value>
      <webElementGuid>7dd6ed55-7228-4b06-aa58-12d456eb36d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dessert&quot;)/h2[@class=&quot;section-header&quot;]</value>
      <webElementGuid>927c415b-162e-4576-a6f3-eea7d0f53c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='dessert']/h2</value>
      <webElementGuid>20280b68-4192-4df1-be63-734c053bcd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD TO CART'])[9]/following::h2[1]</value>
      <webElementGuid>2574d775-4a09-42ab-8e87-cb497dcc62e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$10.00'])[1]/following::h2[1]</value>
      <webElementGuid>d1d41834-fae2-4eb5-a5d7-45ad8aaf5459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mille crepe'])[1]/preceding::h2[1]</value>
      <webElementGuid>2395c2e9-2955-4726-8ab5-63f977ee7685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/h2</value>
      <webElementGuid>71b2c14f-267d-4fed-aa5d-7fa241f57a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Dessert' or . = 'Dessert')]</value>
      <webElementGuid>93945346-6e0e-4279-b7dc-8dcbd3f0206d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
