<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Main Dish</name>
   <tag></tag>
   <elementGuidId>7426d72e-60df-4edc-b9f0-e424069ecdfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainDish > h2.section-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='mainDish']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4898c2d6-ec26-4750-a89c-5cc3c10ebbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>ca02c703-fd62-4554-8e3d-1867bc96cb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Main Dish</value>
      <webElementGuid>59345b78-08ae-4a25-9a28-a4df50247b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainDish&quot;)/h2[@class=&quot;section-header&quot;]</value>
      <webElementGuid>93ef1e1b-bfaa-4eba-a9b9-db8ac6e9783c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='mainDish']/h2</value>
      <webElementGuid>c937ed42-49de-4f0d-9948-5ce5f0693370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD TO CART'])[4]/following::h2[1]</value>
      <webElementGuid>aa4d168b-7780-4a1f-b6c5-843d3a14aff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4.50'])[1]/following::h2[1]</value>
      <webElementGuid>ba1d7b43-6d86-449a-a372-4342bde7bb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAMB BOLOGNESE WITH FETA &amp; MINT'])[1]/preceding::h2[1]</value>
      <webElementGuid>c38cc80e-7ac0-4a72-9aae-5b46d0ee79c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/h2</value>
      <webElementGuid>8e507ccf-99e6-418b-b3f1-9aa804262c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Main Dish' or . = 'Main Dish')]</value>
      <webElementGuid>c0f9e863-ccb1-4189-805b-8a0825aaf2f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
