<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Beverage</name>
   <tag></tag>
   <elementGuidId>fe7ffbdb-a0f3-4385-bed1-a56b7abf672f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beverage > h2.section-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='beverage']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b110b93f-9752-49b5-8a55-fa2ccd160c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>3ba1f983-3e7a-47af-ac64-20ab80391a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beverage</value>
      <webElementGuid>1a11ddf2-a1fb-4c50-a654-2b22e40e16ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beverage&quot;)/h2[@class=&quot;section-header&quot;]</value>
      <webElementGuid>ed6917da-b261-4ed4-92f1-dbf50f712a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='beverage']/h2</value>
      <webElementGuid>d7e17cc0-ed12-4ca4-9a90-1145a8e2b556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD TO CART'])[12]/following::h2[1]</value>
      <webElementGuid>f6c91c4c-3acb-48f4-adf0-48346c3f12be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4.00'])[2]/following::h2[1]</value>
      <webElementGuid>bc4475db-bc76-4f17-aa28-7ad9cf9d39fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orange Juice'])[1]/preceding::h2[1]</value>
      <webElementGuid>2e9e9103-0ce3-4cd3-aa04-4b9127186707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/h2</value>
      <webElementGuid>69154bef-422a-41c6-b9a7-2ea431cbeaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Beverage' or . = 'Beverage')]</value>
      <webElementGuid>4dee709a-63bf-4056-9e4a-cb6b7a1bd420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
