<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Appetizer</name>
   <tag></tag>
   <elementGuidId>8ef42e28-82a4-4f91-9a5c-af35437a8277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.section-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='appetizer']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1b2a3b99-1c98-4ef7-ba90-c52643006f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>2cbc31a2-a62e-4ec8-831b-a1e0c925208b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Appetizer</value>
      <webElementGuid>2dae4346-df23-4ab1-aafd-a72ef3226480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appetizer&quot;)/h2[@class=&quot;section-header&quot;]</value>
      <webElementGuid>253f8c84-b9ff-4189-97b3-ecfeb8d1f8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='appetizer']/h2</value>
      <webElementGuid>c18edba4-3cb8-459a-b177-dab9e37bbf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Page'])[1]/following::h2[1]</value>
      <webElementGuid>6446c953-be9f-43c3-9699-feab0189cb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Order'])[1]/following::h2[1]</value>
      <webElementGuid>21aa88ef-ab40-45b2-96f7-ea109784a962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sticky Baked Chicken Wings'])[1]/preceding::h2[1]</value>
      <webElementGuid>b8e6d8b2-938c-4fc5-8c8b-ea36c8007f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>6482a9b0-1063-4c66-8fc3-ae8ea0c9f29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Appetizer' or . = 'Appetizer')]</value>
      <webElementGuid>bb4aaa98-331f-439b-946c-108c0aaa9355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
