<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>1e9c0254-949d-4043-9713-47e5783966d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.shop-item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;appetizer&quot;]/div/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb5d9938-4819-4b04-999a-30ed983704d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop-item-title</value>
      <webElementGuid>e7d1cb8c-6b07-45d9-bfa7-967b4ee9a96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sticky Baked Chicken Wings</value>
      <webElementGuid>9d0062e7-facd-4027-ac62-764f941420ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appetizer&quot;)/div[@class=&quot;shop-items&quot;]/div[@class=&quot;shop-item&quot;]/span[@class=&quot;shop-item-title&quot;]</value>
      <webElementGuid>3b8583f8-efa3-47e6-a673-a07401a8ef7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='appetizer']/div/div/span</value>
      <webElementGuid>ec5dbe0f-506b-4b07-ae77-bb44bdaf3d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[2]/following::span[1]</value>
      <webElementGuid>f6a3496d-3eaf-411c-aeea-4ae4b22032d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Page'])[1]/following::span[1]</value>
      <webElementGuid>23712d13-b9a4-48db-b277-c3a8b6c0e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3.33'])[1]/preceding::span[1]</value>
      <webElementGuid>9e3e6e02-ca30-4e7f-932b-9a879d0c1584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sticky Baked Chicken Wings']/parent::*</value>
      <webElementGuid>c7e5aed9-5bb6-4453-8436-b46592a41367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>fd8eb797-5f25-465e-b408-f22f45b2b871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sticky Baked Chicken Wings' or . = 'Sticky Baked Chicken Wings')]</value>
      <webElementGuid>c9a8e93a-c872-4615-a83d-8597d0f60321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
