<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Customerpage</name>
   <tag></tag>
   <elementGuidId>f1c98ad9-a25a-4b42-9ea3-fd22a1c61458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success.btn-lg.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Customer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f61eb5e7-d1e2-49a7-a493-69979e3cbd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indexCustomer.ejs</value>
      <webElementGuid>2fb722e0-8e5a-4cde-9301-20cedcb968af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg active</value>
      <webElementGuid>0fe33312-2bfb-46f9-aa27-9ffc8d4f1b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>935ef18d-a6ff-44d3-bd48-d2507c7b63bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea32638e-15ea-45d4-b6f0-190904bdae0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer</value>
      <webElementGuid>e6f01aa6-8857-4686-befa-2f3c997cba72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/a[@class=&quot;btn btn-success btn-lg active&quot;]</value>
      <webElementGuid>6c12aa4a-e6ea-4d38-9e27-d3c30acfed93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer')]</value>
      <webElementGuid>7561f4b8-2161-4098-9ccf-44143e947f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kitchen'])[1]/following::a[1]</value>
      <webElementGuid>51e2b1a9-ebe3-437b-a7dd-0b0bc4756e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select!'])[1]/following::a[2]</value>
      <webElementGuid>36cd1df0-4451-43e3-b192-b26622cf1089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[2]/a[@class=', '&quot;', 'btn btn-success btn-lg active', '&quot;', ']')])[1]/preceding::a[1]</value>
      <webElementGuid>feb7217c-0f2b-4a8c-a96b-5b35772d7940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer']/parent::*</value>
      <webElementGuid>26070dd4-8e9f-427a-b26e-3df820b5b48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indexCustomer.ejs')]</value>
      <webElementGuid>0b3d4fe9-c717-4079-bbee-badf3d4d8b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>e443c353-78ac-46ed-a5cb-9f9b7b6a348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indexCustomer.ejs' and (text() = 'Customer' or . = 'Customer')]</value>
      <webElementGuid>75ef5fb7-8f47-463b-96e2-66d09a9aaa3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
