<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refresh Page</name>
   <tag></tag>
   <elementGuidId>b632bed3-0dd8-4cd2-8676-9c67884e9c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.d-flex > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='window.location.reload();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb3dc2e6-6933-4129-881b-f5f0dbe23cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location.reload();</value>
      <webElementGuid>8798c1a2-1bfd-4c8e-a1d5-387096507b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh Page</value>
      <webElementGuid>e9deabbd-e1fc-4daf-a71c-8dd713c634ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/form[@class=&quot;d-flex&quot;]/button[1]</value>
      <webElementGuid>0297ec4a-ddc8-48b5-b713-7c45772de8a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='window.location.reload();']</value>
      <webElementGuid>c07fab2f-dd7d-462f-be93-489478359ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/form/button</value>
      <webElementGuid>d6a820c3-e1b3-4ac9-b430-7030b5b7760a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Order'])[1]/following::button[1]</value>
      <webElementGuid>3c25eda1-7c92-4cd8-be30-d9b3be0c6d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beverage'])[1]/following::button[1]</value>
      <webElementGuid>460fad38-07d0-4122-9c94-75996d94aa41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[2]/preceding::button[1]</value>
      <webElementGuid>c1d86899-7b94-4dc4-94dd-2194d2f66ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sticky Baked Chicken Wings'])[1]/preceding::button[1]</value>
      <webElementGuid>8d4cdf9a-efca-40ed-9fb3-f8f8ca3cc3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh Page']/parent::*</value>
      <webElementGuid>2f2c545d-ddb4-46ab-87a9-c96aa6a46749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>d01636b5-3092-4470-aae6-21b3135ee92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Refresh Page' or . = 'Refresh Page')]</value>
      <webElementGuid>8fa78010-54e6-4a03-9659-2e318b7ab601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
