<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sticky Baked Chicken Wings</name>
   <tag></tag>
   <elementGuidId>f2c11835-d230-42c3-a439-80e652adf886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.shop-item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='appetizer']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3214a5eb-e1cc-48d5-bbf3-3e949c8067bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop-item-title</value>
      <webElementGuid>162567e9-4bbf-4023-aa14-a3d168738df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sticky Baked Chicken Wings</value>
      <webElementGuid>b261e09d-2f0b-42e1-89a4-873f716e06e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appetizer&quot;)/div[@class=&quot;shop-items&quot;]/div[@class=&quot;shop-item&quot;]/span[@class=&quot;shop-item-title&quot;]</value>
      <webElementGuid>846b66d6-aba9-481d-a56a-db3b87c35ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='appetizer']/div/div/span</value>
      <webElementGuid>8d68ab2f-6b16-41e4-b163-b814b0da5fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[2]/following::span[1]</value>
      <webElementGuid>6fbda594-caf9-4dda-b773-5902de0005e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Page'])[1]/following::span[1]</value>
      <webElementGuid>771e2425-3822-45a1-a21e-81c6e4eb3149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3.33'])[1]/preceding::span[1]</value>
      <webElementGuid>bcdb7fc6-c844-4d0f-a548-5232928e0d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sticky Baked Chicken Wings']/parent::*</value>
      <webElementGuid>016ecc63-367f-42d5-b4a9-fa385a784127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>2631169e-1e2c-4da2-b260-cd91e971cedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sticky Baked Chicken Wings' or . = 'Sticky Baked Chicken Wings')]</value>
      <webElementGuid>ef87c505-ebc4-4612-b96c-3facb9db0def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
