<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My Order_search</name>
   <tag></tag>
   <elementGuidId>7774d05e-4cdb-41a4-98fd-42639b1a571c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>554242f0-4b9d-4e4b-87ed-2ba6d8b8fed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBar</value>
      <webElementGuid>255129e4-95b2-44f2-adad-3d65008a20fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>95e84d6e-2877-4fcf-b10d-4b587966cb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>search_food_info()</value>
      <webElementGuid>3e81aa27-1e09-4011-a54a-10348bb49c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control me-2</value>
      <webElementGuid>fdcf8151-a57e-47c4-9412-3946649a9622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c1a8c59d-c46c-4949-8ec1-b3ad560b8e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Food</value>
      <webElementGuid>af3368a8-f6b6-4181-8e85-a96b12c7ae1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>57d46a59-d5d9-48ca-aa31-11d5e66f4857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBar&quot;)</value>
      <webElementGuid>a54a9d88-1ea0-4f87-804d-eb33868e21d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBar']</value>
      <webElementGuid>73c8dbf4-d30e-467d-9670-a195844509d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/form/input</value>
      <webElementGuid>f94335bf-d5c8-4962-8f53-721e7def374a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d8d623bf-bfa1-49b4-8a45-b4dfe5f8e49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchBar' and @name = 'search' and @type = 'search' and @placeholder = 'Search Food']</value>
      <webElementGuid>2c944eb4-c0cb-47a5-a728-d74837ba8bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
