<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Customer</name>
   <tag></tag>
   <elementGuidId>0c0a12a0-20c7-47e8-8950-973f2085fcc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success.btn-lg.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Customer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f9e1698-ce68-4c1c-a67c-092553caae3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indexCustomer.ejs</value>
      <webElementGuid>9475b492-e157-4b43-b769-75e9fd774d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg active</value>
      <webElementGuid>66955ca6-c7bc-4e67-89b2-9bbe923d2a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e4290c6-075c-44b1-9570-90c220c3f035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba6e1f59-b29c-4b03-81c7-66f1682b4854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer</value>
      <webElementGuid>53edaed7-df45-460e-8d04-181564c09318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/a[@class=&quot;btn btn-success btn-lg active&quot;]</value>
      <webElementGuid>da89a9a6-872a-403e-8b2c-36459ba5eddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer')]</value>
      <webElementGuid>0af56199-a9f2-4fa6-8db5-04f861a55575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kitchen'])[1]/following::a[1]</value>
      <webElementGuid>e1f11cd8-2cfa-4ad0-80db-962825a0d3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select!'])[1]/following::a[2]</value>
      <webElementGuid>e216dd2a-4cc3-4a07-b46a-261b24c16329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[2]/a[@class=', '&quot;', 'btn btn-success btn-lg active', '&quot;', ']')])[1]/preceding::a[1]</value>
      <webElementGuid>6052502d-0b5f-4140-9af3-ac40ae608b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer']/parent::*</value>
      <webElementGuid>0ecf499b-d733-4b47-887e-cbdda94aa03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indexCustomer.ejs')]</value>
      <webElementGuid>b7adb083-56e8-45cb-99ee-f24093a543b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>dea82f84-921e-43b2-bc59-b2f0eeba681b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indexCustomer.ejs' and (text() = 'Customer' or . = 'Customer')]</value>
      <webElementGuid>9c83b783-f579-4dc4-aaf6-811a3d2fc7cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
